// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/analizador/lexico.jflex

package analizador;

// importaciones
import java_cup.runtime.Symbol;
import java.util.LinkedList;
import excepciones.Errores;
import tokens.Tokens;


@SuppressWarnings("fallthrough")
public class scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int CADENA = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  3,  4,  4,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     1,  5,  6,  0,  7,  8,  9, 10, 11, 12, 13, 14,  0, 15, 16, 17, 
    18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19, 20, 21, 22, 23,  0, 
     0, 24, 25, 26, 27, 28, 29, 30, 31, 32,  0,  0, 33, 34, 35, 36, 
     0,  0, 37, 38, 39, 40,  0, 41,  0,  0,  0,  0, 42,  0, 43, 44, 
     0, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 54, 55, 56, 57, 58, 
    54, 54, 59, 60, 61, 62, 54, 63, 54, 54, 54, 64, 65, 66,  0,  0, 
     0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\1\1\4\1\5\2\1"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\13\1\1\22\14\23\1\24"+
    "\1\1\1\25\1\0\1\26\1\0\1\27\1\0\1\30"+
    "\1\0\1\31\1\32\1\0\1\33\1\0\1\34\1\35"+
    "\1\36\1\37\1\40\4\0\1\41\3\0\1\42\6\0"+
    "\1\40\4\23\1\41\3\23\1\42\6\23\1\43\1\44"+
    "\1\0\1\45\7\0\1\46\1\47\1\50\4\0\7\23"+
    "\1\46\1\47\1\50\4\23\1\51\1\52\1\53\3\0"+
    "\1\54\2\0\1\55\1\0\1\52\1\53\3\23\1\54"+
    "\2\23\1\55\1\23\1\0\1\56\2\0\1\57\1\0"+
    "\1\60\1\23\1\56\2\23\1\57\1\23\1\60\2\0"+
    "\1\61\1\62\2\23\1\61\1\62\1\0\1\63\1\23"+
    "\1\63\3\0\1\64";

  private static int [] zzUnpackAction() {
    int [] result = new int[180];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\103\0\206\0\311\0\u010c\0\u014f\0\206\0\206"+
    "\0\u0192\0\u01d5\0\206\0\206\0\206\0\u0218\0\u025b\0\u029e"+
    "\0\u02e1\0\206\0\206\0\u0324\0\u0367\0\u03aa\0\u03ed\0\u0430"+
    "\0\u0473\0\u04b6\0\u04f9\0\u053c\0\u057f\0\u05c2\0\u0605\0\u0648"+
    "\0\u068b\0\206\0\u06ce\0\u0711\0\u0754\0\u0797\0\u07da\0\u081d"+
    "\0\u0860\0\u08a3\0\u08e6\0\u0929\0\u096c\0\u09af\0\206\0\u09f2"+
    "\0\206\0\u029e\0\206\0\u014f\0\206\0\u0a35\0\206\0\u0a78"+
    "\0\206\0\206\0\u0abb\0\u0afe\0\u0b41\0\206\0\206\0\206"+
    "\0\206\0\206\0\u0b84\0\u0bc7\0\u0c0a\0\u0c4d\0\u0c90\0\u0cd3"+
    "\0\u0d16\0\u0d59\0\206\0\u0d9c\0\u0ddf\0\u0e22\0\u0e65\0\u0ea8"+
    "\0\u0eeb\0\u0711\0\u0f2e\0\u0f71\0\u0fb4\0\u0ff7\0\u103a\0\u107d"+
    "\0\u10c0\0\u1103\0\u0711\0\u1146\0\u1189\0\u11cc\0\u120f\0\u1252"+
    "\0\u1295\0\206\0\206\0\u12d8\0\u0b41\0\u131b\0\u135e\0\u13a1"+
    "\0\u13e4\0\u1427\0\u146a\0\u14ad\0\206\0\206\0\206\0\u14f0"+
    "\0\u1533\0\u1576\0\u15b9\0\u15fc\0\u163f\0\u1682\0\u16c5\0\u1708"+
    "\0\u174b\0\u178e\0\u0711\0\u0711\0\u0711\0\u17d1\0\u1814\0\u1857"+
    "\0\u189a\0\206\0\206\0\206\0\u18dd\0\u1920\0\u1963\0\206"+
    "\0\u19a6\0\u19e9\0\206\0\u1a2c\0\u0711\0\u0711\0\u1a6f\0\u1ab2"+
    "\0\u1af5\0\u0711\0\u1b38\0\u1b7b\0\u0711\0\u1bbe\0\u1c01\0\206"+
    "\0\u1c44\0\u1c87\0\206\0\u1cca\0\206\0\u1d0d\0\u0711\0\u1d50"+
    "\0\u1d93\0\u0711\0\u1dd6\0\u0711\0\u1e19\0\u1e5c\0\206\0\206"+
    "\0\u1e9f\0\u1ee2\0\u0711\0\u0711\0\u1f25\0\206\0\u1f68\0\u0711"+
    "\0\u1fab\0\u1fee\0\u2031\0\206";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[180];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\3"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\3\1\30\1\31\1\32\1\33\2\3\1\34\1\35"+
    "\1\36\3\3\1\37\1\40\1\3\1\41\1\3\1\42"+
    "\1\3\1\43\1\44\1\45\1\46\1\47\1\50\2\44"+
    "\1\51\1\44\1\52\1\53\3\44\1\54\1\55\1\44"+
    "\1\56\1\57\1\60\1\61\21\0\1\62\165\0\2\4"+
    "\1\0\1\4\124\0\1\63\54\0\6\64\1\65\43\64"+
    "\1\66\30\64\11\0\1\67\71\0\12\70\1\0\70\70"+
    "\16\0\1\71\103\0\1\72\100\0\1\73\3\0\1\74"+
    "\101\0\1\75\1\0\1\21\106\0\1\76\102\0\1\77"+
    "\1\100\101\0\1\101\122\0\1\102\25\0\1\102\36\0"+
    "\1\103\6\0\1\104\4\0\1\105\10\0\1\103\6\0"+
    "\1\104\5\0\1\105\44\0\1\106\7\0\1\107\14\0"+
    "\1\106\10\0\1\107\51\0\1\110\25\0\1\110\43\0"+
    "\1\111\13\0\1\112\10\0\1\111\14\0\1\112\45\0"+
    "\1\113\5\0\1\114\16\0\1\113\6\0\1\114\45\0"+
    "\1\115\24\0\1\115\51\0\1\116\24\0\1\116\74\0"+
    "\1\117\25\0\1\117\52\0\1\120\25\0\1\120\46\0"+
    "\1\121\24\0\1\121\40\0\1\44\23\0\1\102\5\0"+
    "\20\44\1\122\3\44\25\0\1\44\31\0\24\44\25\0"+
    "\1\44\5\0\1\103\6\0\1\104\4\0\1\105\7\0"+
    "\1\44\1\123\6\44\1\124\5\44\1\125\5\44\25\0"+
    "\1\44\11\0\1\106\7\0\1\107\7\0\5\44\1\126"+
    "\10\44\1\127\5\44\25\0\1\44\16\0\1\110\12\0"+
    "\13\44\1\130\10\44\25\0\1\44\5\0\1\111\13\0"+
    "\1\112\7\0\1\44\1\131\14\44\1\132\5\44\25\0"+
    "\1\44\12\0\1\113\5\0\1\114\10\0\6\44\1\133"+
    "\6\44\1\134\6\44\25\0\1\44\11\0\1\115\17\0"+
    "\5\44\1\135\16\44\25\0\1\44\5\0\1\116\23\0"+
    "\1\44\1\136\22\44\25\0\1\44\24\0\1\117\4\0"+
    "\21\44\1\137\2\44\25\0\1\44\22\0\1\120\6\0"+
    "\17\44\1\140\4\44\25\0\1\44\14\0\1\121\14\0"+
    "\10\44\1\141\13\44\104\0\1\142\1\0\2\64\3\0"+
    "\76\64\12\0\1\143\70\0\15\73\1\144\65\73\2\74"+
    "\1\0\100\74\22\0\1\145\126\0\1\146\25\0\1\146"+
    "\36\0\1\147\24\0\1\147\70\0\1\150\25\0\1\150"+
    "\46\0\1\151\24\0\1\151\70\0\1\152\25\0\1\152"+
    "\52\0\1\153\25\0\1\153\47\0\1\154\25\0\1\154"+
    "\60\0\1\155\25\0\1\155\56\0\1\156\25\0\1\156"+
    "\54\0\1\157\25\0\1\157\54\0\1\160\25\0\1\160"+
    "\52\0\1\161\25\0\1\161\57\0\1\162\25\0\1\162"+
    "\44\0\1\163\24\0\1\163\37\0\1\44\23\0\1\146"+
    "\5\0\20\44\1\164\3\44\25\0\1\44\5\0\1\147"+
    "\23\0\1\44\1\165\22\44\25\0\1\44\20\0\1\150"+
    "\10\0\15\44\1\166\6\44\25\0\1\44\12\0\1\151"+
    "\16\0\6\44\1\167\15\44\25\0\1\44\25\0\1\152"+
    "\3\0\22\44\1\170\1\44\25\0\1\44\23\0\1\153"+
    "\5\0\20\44\1\171\3\44\25\0\1\44\16\0\1\154"+
    "\12\0\13\44\1\172\10\44\25\0\1\44\22\0\1\155"+
    "\6\0\17\44\1\173\4\44\25\0\1\44\24\0\1\156"+
    "\4\0\21\44\1\174\2\44\25\0\1\44\24\0\1\157"+
    "\4\0\21\44\1\175\2\44\25\0\1\44\24\0\1\160"+
    "\4\0\21\44\1\176\2\44\25\0\1\44\22\0\1\161"+
    "\6\0\17\44\1\177\4\44\25\0\1\44\25\0\1\162"+
    "\3\0\22\44\1\200\1\44\25\0\1\44\15\0\1\163"+
    "\13\0\11\44\1\201\12\44\3\0\21\73\1\202\61\73"+
    "\47\0\1\203\25\0\1\203\52\0\1\204\25\0\1\204"+
    "\55\0\1\205\25\0\1\205\36\0\1\206\24\0\1\206"+
    "\56\0\1\207\24\0\1\207\60\0\1\210\24\0\1\210"+
    "\67\0\1\162\25\0\1\162\40\0\1\211\24\0\1\211"+
    "\63\0\1\212\24\0\1\212\51\0\1\213\24\0\1\213"+
    "\62\0\1\214\25\0\1\214\35\0\1\44\24\0\1\203"+
    "\4\0\21\44\1\215\2\44\25\0\1\44\22\0\1\204"+
    "\6\0\17\44\1\216\4\44\25\0\1\44\23\0\1\205"+
    "\5\0\20\44\1\217\3\44\25\0\1\44\5\0\1\206"+
    "\23\0\1\44\1\220\22\44\25\0\1\44\6\0\1\207"+
    "\22\0\2\44\1\221\21\44\25\0\1\44\11\0\1\210"+
    "\17\0\5\44\1\222\16\44\25\0\1\44\23\0\1\162"+
    "\5\0\20\44\1\200\3\44\25\0\1\44\7\0\1\211"+
    "\21\0\3\44\1\223\20\44\25\0\1\44\15\0\1\212"+
    "\13\0\11\44\1\224\12\44\25\0\1\44\11\0\1\213"+
    "\17\0\5\44\1\225\16\44\25\0\1\44\16\0\1\214"+
    "\12\0\13\44\1\226\10\44\47\0\1\227\2\0\1\230"+
    "\22\0\1\227\2\0\1\230\55\0\1\231\25\0\1\231"+
    "\45\0\1\232\25\0\1\232\52\0\1\233\24\0\1\233"+
    "\61\0\1\234\25\0\1\234\45\0\1\235\24\0\1\235"+
    "\43\0\1\44\21\0\1\227\2\0\1\230\4\0\16\44"+
    "\1\236\2\44\1\237\2\44\25\0\1\44\25\0\1\231"+
    "\3\0\22\44\1\240\1\44\25\0\1\44\16\0\1\232"+
    "\12\0\13\44\1\241\10\44\25\0\1\44\14\0\1\233"+
    "\14\0\10\44\1\242\13\44\25\0\1\44\20\0\1\234"+
    "\10\0\15\44\1\243\6\44\25\0\1\44\11\0\1\235"+
    "\17\0\5\44\1\244\16\44\44\0\1\245\25\0\1\245"+
    "\54\0\1\246\25\0\1\246\47\0\1\247\24\0\1\247"+
    "\57\0\1\250\24\0\1\250\41\0\1\44\16\0\1\245"+
    "\12\0\13\44\1\251\10\44\25\0\1\44\16\0\1\246"+
    "\12\0\13\44\1\252\10\44\25\0\1\44\11\0\1\247"+
    "\17\0\5\44\1\253\16\44\25\0\1\44\13\0\1\250"+
    "\15\0\7\44\1\254\14\44\37\0\1\255\24\0\1\255"+
    "\70\0\1\256\25\0\1\256\27\0\1\44\11\0\1\255"+
    "\17\0\5\44\1\257\16\44\25\0\1\44\24\0\1\256"+
    "\4\0\21\44\1\260\2\44\23\0\1\261\102\0\1\261"+
    "\1\0\1\44\31\0\24\44\44\0\1\262\25\0\1\262"+
    "\57\0\1\263\25\0\1\263\46\0\1\264\24\0\1\264"+
    "\17\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[8308];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\3\1\2\11\2\1\3\11\4\1\2\11"+
    "\16\1\1\11\14\1\1\11\1\1\1\11\1\0\1\11"+
    "\1\0\1\11\1\0\1\11\1\0\2\11\1\0\1\1"+
    "\1\0\5\11\4\0\1\1\3\0\1\11\6\0\20\1"+
    "\2\11\1\0\1\1\7\0\3\11\4\0\16\1\3\11"+
    "\3\0\1\11\2\0\1\11\1\0\12\1\1\0\1\11"+
    "\2\0\1\11\1\0\1\11\7\1\2\0\2\11\4\1"+
    "\1\0\1\11\2\1\3\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[180];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    public LinkedList<Errores> erroresLexicos = new LinkedList<>();
    public LinkedList<Tokens> MisTokens = new LinkedList<>();


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public scanner(java.io.Reader in) {
      yyline = 1;
    yycolumn = 1;
    erroresLexicos = new LinkedList<>();
    MisTokens = new LinkedList<>();
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    return ZZ_CMAP[input];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { erroresLexicos.add(new Errores("LEXICO", "El caracter "+ yytext() + " no pertenece al lenguaje", yyline, yycolumn));
            }
          // fall through
          case 53: break;
          case 2:
            { 
            }
          // fall through
          case 54: break;
          case 3:
            { MisTokens.add(new Tokens("NOT",yytext(), yyline, yycolumn));
                                return new Symbol(sym.NOT, yyline, yycolumn, yytext());
            }
          // fall through
          case 55: break;
          case 4:
            { MisTokens.add(new Tokens("RAIZ",yytext(), yyline, yycolumn));
                                return new Symbol(sym.RAIZ, yyline, yycolumn, yytext());
            }
          // fall through
          case 56: break;
          case 5:
            { MisTokens.add(new Tokens("MODULO",yytext(), yyline, yycolumn));
                                return new Symbol(sym.MODULO, yyline, yycolumn, yytext());
            }
          // fall through
          case 57: break;
          case 6:
            { MisTokens.add(new Tokens("PAR1",yytext(), yyline, yycolumn));
                              return new Symbol(sym.PAR1, yyline, yycolumn, yytext());
            }
          // fall through
          case 58: break;
          case 7:
            { MisTokens.add(new Tokens("PAR2",yytext(), yyline, yycolumn));
                              return new Symbol(sym.PAR2, yyline, yycolumn, yytext());
            }
          // fall through
          case 59: break;
          case 8:
            { MisTokens.add(new Tokens("POR",yytext(), yyline, yycolumn));
                                return new Symbol(sym.POR, yyline, yycolumn, yytext());
            }
          // fall through
          case 60: break;
          case 9:
            { MisTokens.add(new Tokens("MAS",yytext(), yyline, yycolumn));
                                return new Symbol(sym.MAS, yyline, yycolumn, yytext());
            }
          // fall through
          case 61: break;
          case 10:
            { MisTokens.add(new Tokens("MENOS",yytext(), yyline, yycolumn));
                               return new Symbol(sym.MENOS, yyline, yycolumn, yytext());
            }
          // fall through
          case 62: break;
          case 11:
            { MisTokens.add(new Tokens("DIVISION",yytext(), yyline, yycolumn));
                                return new Symbol(sym.DIVISION, yyline, yycolumn, yytext());
            }
          // fall through
          case 63: break;
          case 12:
            { MisTokens.add(new Tokens("ENTERO",yytext(), yyline, yycolumn));
                                return new Symbol(sym.ENTERO, yyline, yycolumn, yytext());
            }
          // fall through
          case 64: break;
          case 13:
            { MisTokens.add(new Tokens("COLOM",yytext(), yyline, yycolumn));
                              return new Symbol(sym.COLOM, yyline, yycolumn, yytext());
            }
          // fall through
          case 65: break;
          case 14:
            { MisTokens.add(new Tokens("FINCADENA",yytext(), yyline, yycolumn));
                              return new Symbol(sym.FINCADENA, yyline, yycolumn, yytext());
            }
          // fall through
          case 66: break;
          case 15:
            { MisTokens.add(new Tokens("MENOR",yytext(), yyline, yycolumn));
                                return new Symbol(sym.MENOR, yyline, yycolumn, yytext());
            }
          // fall through
          case 67: break;
          case 16:
            { MisTokens.add(new Tokens("IGUAL",yytext(), yyline, yycolumn));
                                return new Symbol(sym.IGUAL, yyline, yycolumn, yytext());
            }
          // fall through
          case 68: break;
          case 17:
            { MisTokens.add(new Tokens("MAYOR",yytext(), yyline, yycolumn));
                                return new Symbol(sym.MAYOR, yyline, yycolumn, yytext());
            }
          // fall through
          case 69: break;
          case 18:
            { MisTokens.add(new Tokens("POTENCIA",yytext(), yyline, yycolumn));
                                return new Symbol(sym.POTENCIA, yyline, yycolumn, yytext());
            }
          // fall through
          case 70: break;
          case 19:
            { MisTokens.add(new Tokens("ID",yytext(), yyline, yycolumn));
                                return new Symbol(sym.ID, yyline, yycolumn, yytext());
            }
          // fall through
          case 71: break;
          case 20:
            { MisTokens.add(new Tokens("LKEY",yytext(), yyline, yycolumn));
                              return new Symbol(sym.LKEY, yyline, yycolumn, yytext());
            }
          // fall through
          case 72: break;
          case 21:
            { MisTokens.add(new Tokens("RKEY",yytext(), yyline, yycolumn));
                              return new Symbol(sym.RKEY, yyline, yycolumn, yytext());
            }
          // fall through
          case 73: break;
          case 22:
            { MisTokens.add(new Tokens("DIFERENCIA",yytext(), yyline, yycolumn));
                                return new Symbol(sym.DIFERENCIA, yyline, yycolumn, yytext());
            }
          // fall through
          case 74: break;
          case 23:
            { String cadena = yytext(); 
                             cadena=cadena.substring(1, cadena.length() - 1);
                             cadena = cadena.replace("\\n", "\n")
                                             .replace("\\t", "\t")
                                             .replace("\\\\", "\\\\")
                                             .replace("\\\"", "\"")
                                             .replace("\\'", "'");
                             MisTokens.add(new Tokens("CADENA",cadena, yyline, yycolumn));
                             return new Symbol(sym.CADENA, yyline, yycolumn, cadena);
            }
          // fall through
          case 75: break;
          case 24:
            { MisTokens.add(new Tokens("AND",yytext(), yyline, yycolumn));
                                return new Symbol(sym.AND, yyline, yycolumn, yytext());
            }
          // fall through
          case 76: break;
          case 25:
            { MisTokens.add(new Tokens("INCREMENTO",yytext(), yyline, yycolumn));
                                return new Symbol(sym.INCREMENTO, yyline, yycolumn, yytext());
            }
          // fall through
          case 77: break;
          case 26:
            { MisTokens.add(new Tokens("DECREMENTO",yytext(), yyline, yycolumn));
                                return new Symbol(sym.DECREMENTO, yyline, yycolumn, yytext());
            }
          // fall through
          case 78: break;
          case 27:
            { /* Ignorar comentarios de una línea */
            }
          // fall through
          case 79: break;
          case 28:
            { MisTokens.add(new Tokens("MENORIGUAL",yytext(), yyline, yycolumn));
                                return new Symbol(sym.MENORIGUAL, yyline, yycolumn, yytext());
            }
          // fall through
          case 80: break;
          case 29:
            { MisTokens.add(new Tokens("IGUALACION",yytext(), yyline, yycolumn));
                                return new Symbol(sym.IGUALACION, yyline, yycolumn, yytext());
            }
          // fall through
          case 81: break;
          case 30:
            { MisTokens.add(new Tokens("TO",yytext(), yyline, yycolumn));
                                return new Symbol(sym.TO, yyline, yycolumn, yytext());
            }
          // fall through
          case 82: break;
          case 31:
            { MisTokens.add(new Tokens("MAYORIGUAL",yytext(), yyline, yycolumn));
                                return new Symbol(sym.MAYORIGUAL, yyline, yycolumn, yytext());
            }
          // fall through
          case 83: break;
          case 32:
            { MisTokens.add(new Tokens("AS",yytext(), yyline, yycolumn));
                                return new Symbol(sym.AS, yyline, yycolumn, yytext());
            }
          // fall through
          case 84: break;
          case 33:
            { MisTokens.add(new Tokens("DO",yytext(), yyline, yycolumn));
                                return new Symbol(sym.DO, yyline, yycolumn, yytext());
            }
          // fall through
          case 85: break;
          case 34:
            { MisTokens.add(new Tokens("IF",yytext(), yyline, yycolumn));
                                return new Symbol(sym.IF, yyline, yycolumn, yytext());
            }
          // fall through
          case 86: break;
          case 35:
            { MisTokens.add(new Tokens("OR",yytext(), yyline, yycolumn));
                                return new Symbol(sym.OR, yyline, yycolumn, yytext());
            }
          // fall through
          case 87: break;
          case 36:
            { String caracter = yytext(); 
                             caracter=caracter.substring(1, caracter.length() - 1);
                             MisTokens.add(new Tokens("CARACTER",caracter, yyline, yycolumn));
                             return new Symbol(sym.CARACTER, yyline, yycolumn, caracter);
            }
          // fall through
          case 88: break;
          case 37:
            { MisTokens.add(new Tokens("DECIMAL",yytext(), yyline, yycolumn));
                                return new Symbol(sym.DECIMAL, yyline, yycolumn, yytext());
            }
          // fall through
          case 89: break;
          case 38:
            { MisTokens.add(new Tokens("FOR",yytext(), yyline, yycolumn));
                                return new Symbol(sym.FOR, yyline, yycolumn, yytext());
            }
          // fall through
          case 90: break;
          case 39:
            { MisTokens.add(new Tokens("INT",yytext(), yyline, yycolumn));
                                return new Symbol(sym.INT, yyline, yycolumn, yytext());
            }
          // fall through
          case 91: break;
          case 40:
            { MisTokens.add(new Tokens("LET",yytext(), yyline, yycolumn));
                                return new Symbol(sym.LET, yyline, yycolumn, yytext());
            }
          // fall through
          case 92: break;
          case 41:
            { /* Ignorar comentarios de múltiples líneas */
            }
          // fall through
          case 93: break;
          case 42:
            { MisTokens.add(new Tokens("CAST",yytext(), yyline, yycolumn));
                                return new Symbol(sym.CAST, yyline, yycolumn, yytext());
            }
          // fall through
          case 94: break;
          case 43:
            { MisTokens.add(new Tokens("CHAR",yytext(), yyline, yycolumn));
                                return new Symbol(sym.CHAR, yyline, yycolumn, yytext());
            }
          // fall through
          case 95: break;
          case 44:
            { MisTokens.add(new Tokens("ELSE",yytext(), yyline, yycolumn));
                                return new Symbol(sym.ELSE, yyline, yycolumn, yytext());
            }
          // fall through
          case 96: break;
          case 45:
            { MisTokens.add(new Tokens("BOOLEANO",yytext(), yyline, yycolumn));
                                return new Symbol(sym.BOOLEANO, yyline, yycolumn, yytext());
            }
          // fall through
          case 97: break;
          case 46:
            { MisTokens.add(new Tokens("CONST",yytext(), yyline, yycolumn));
                                return new Symbol(sym.CONST, yyline, yycolumn, yytext());
            }
          // fall through
          case 98: break;
          case 47:
            { MisTokens.add(new Tokens("MATCH",yytext(), yyline, yycolumn));
                                return new Symbol(sym.MATCH, yyline, yycolumn, yytext());
            }
          // fall through
          case 99: break;
          case 48:
            { MisTokens.add(new Tokens("WHILE",yytext(), yyline, yycolumn));
                                return new Symbol(sym.WHILE, yyline, yycolumn, yytext());
            }
          // fall through
          case 100: break;
          case 49:
            { MisTokens.add(new Tokens("DOUBLE",yytext(), yyline, yycolumn));
                                return new Symbol(sym.DOUBLE, yyline, yycolumn, yytext());
            }
          // fall through
          case 101: break;
          case 50:
            { MisTokens.add(new Tokens("STRING",yytext(), yyline, yycolumn));
                                return new Symbol(sym.STRING, yyline, yycolumn, yytext());
            }
          // fall through
          case 102: break;
          case 51:
            { MisTokens.add(new Tokens("DEFAULT",yytext(), yyline, yycolumn));
                                return new Symbol(sym.DEFAULT, yyline, yycolumn, yytext());
            }
          // fall through
          case 103: break;
          case 52:
            { MisTokens.add(new Tokens("IMPRIMIR",yytext(), yyline, yycolumn));
                                return new Symbol(sym.IMPRIMIR, yyline, yycolumn, yytext());
            }
          // fall through
          case 104: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
