
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 12;
  public static final int DIFERENCIA = 20;
  public static final int RAIZ = 17;
  public static final int CADENA = 3;
  public static final int FINCADENA = 7;
  public static final int DECIMAL = 5;
  public static final int DIVISION = 15;
  public static final int POTENCIA = 16;
  public static final int IMPRIMIR = 8;
  public static final int MODULO = 18;
  public static final int UMENOS = 13;
  public static final int POR = 14;
  public static final int BOOLEANO = 6;
  public static final int CARACTER = 2;
  public static final int MAYOR = 21;
  public static final int EOF = 0;
  public static final int IGUALACION = 19;
  public static final int MAYORIGUAL = 22;
  public static final int error = 1;
  public static final int PAR2 = 10;
  public static final int PAR1 = 9;
  public static final int ENTERO = 4;
  public static final int MAS = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CARACTER",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "BOOLEANO",
  "FINCADENA",
  "IMPRIMIR",
  "PAR1",
  "PAR2",
  "MAS",
  "MENOS",
  "UMENOS",
  "POR",
  "DIVISION",
  "POTENCIA",
  "RAIZ",
  "MODULO",
  "IGUALACION",
  "DIFERENCIA",
  "MAYOR",
  "MAYORIGUAL"
  };
}

